### ISSUE TITLE
How can I export layer's width, height, and x and y position in a JSON file?

### ISSUE THREAD

**Issue by forethoughtde** [jwa107/Photoshop-Export-Layers-to-Files-Fast#119] opened 2018-09-19 17:13 UTC
I have a situation where I have to export layer's width, height and x and y position in a JSON file along with layers in PNG? 

Is it possible to do with this script? Can you please give me any pointer on how to approach with your script if it is not possible so that I can develop that feature and make a push request ? 

Thanks

**Comment by jwa107** [comment] 2018-09-20 18:55
Duplicate of: https://github.com/jwa107/Photoshop-Export-Layers-to-Files-Fast/issues/114

As far as your question goes, there's a layer collection process that collects all the relevant layers -- those then get looped over and saved as images by the script. At this point you could probably collect the coordinates and height/width of the layer and push it into a JSON or TXT file and save that out as well.

**Closed by jwa107** 2018-09-20 18:55 UTC
Labels: duplicate
